### PR TITLE
some accumulated fixes

### PR DESCRIPTION
**Pull request by irixxxx**
Hey, it's been some time. Just thought you might be interested, although you have apparently already merged some of it some month ago.

However, the latest 2 fix a problem in the file selector where an endless loop may occur if an alpha search key is pressed on the 1st entry of the dirlist and no file matches. And menu key handling in the file selector was allowing 2 operations at once if a directional key also had a CHAR key mapping.

Is there a reason why a menu key is allowed to have a char mapping in the menu key translate ? I'd probably return either a menu key or a charcode.

### CODE REVIEW

**Comment by notaz** [comment]
Hmm there are conflicts so can you pre-merge or rebase?

I don't remember most if this code, but from a quick look your changes look good. I can't recall the char mapping thing either, could be an oversight. Will try all this in pcsx-rearmed standalone when I can get back to it.

**Comment by irixxxx** [comment]
> Hmm there are conflicts so can you pre-merge or rebase?

Yes, I saw this. The conflict is trivial though, which is why I ignored it. I'll look at it.

> I don't remember most if this code, but from a quick look your changes look good. I can't recall the char mapping thing either, could be an oversight. Will try all this in pcsx-rearmed standalone when I can get back to it.

It made problems with opendingux devices, where keys are named with one-char strings like "L" and "R". The intended function of those keys was overwritten by the CHAR mapping executed last.

**Comment by irixxxx** [comment]
Regarding char mapping, [this patch](https://git.crowdedwood.com/picoarch/tree/patches/libpicofe/0003-avoid-button-conflict.patch) would remove char mappings for menu keys. Is this looking OK for you?

**Comment by notaz** [comment]
Looking at the char stuff it seems like it was intentional. Perhaps for entering some menu screen for text input and in case for mappings like
```
  { SDLK_SEMICOLON,    PBTN_MA2 },
  { SDLK_QUOTE,        PBTN_MA3 },
  { SDLK_LEFTBRACKET,  PBTN_L },
  { SDLK_RIGHTBRACKET, PBTN_R },
```
to be able to type quote, semicolon and brackets. However this doesn't matter as such text input screen was never needed.

**Comment by irixxxx** [comment]
Yes that would indeed be the case. However, it's now working with the commits in this PR, so changes to this wouldn't be necessary anyway.
It might even come in the way when I'm finally going to process the PR for adding keyboard support I have on my copy for some time. It's just too specialized for the Pico keyboard and I'd want to be able to use this for adding SC3000 support as well. I haven't made up my mind what the best way for handing this would be.

**Pull request merged**
